# Generated by Django 2.1 on 2018-08-26 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('name', models.CharField(help_text='客户名称', max_length=20, null=True, unique=True, verbose_name='客户名称')),
                ('tontact_phone', models.CharField(blank=True, help_text='联系电话', max_length=20, null=True, verbose_name='联系电话')),
                ('contact_name', models.CharField(blank=True, help_text='联系人', max_length=20, null=True, verbose_name='联系人')),
                ('address', models.CharField(blank=True, help_text='地址', max_length=20, null=True, verbose_name='地址')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('name', models.CharField(help_text='仓库名称', max_length=60, null=True, unique=True, verbose_name='仓库名称')),
                ('type', models.CharField(choices=[('main', '在途'), ('branch', '总库')], default='main', help_text='仓库类型', max_length=20, verbose_name='仓库类型')),
                ('stock', models.IntegerField(default=0, help_text='库存', verbose_name='库存')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('invoice', models.CharField(help_text='单位名称', max_length=100, null=True, unique=True, verbose_name='票号')),
                ('tontact_phone', models.CharField(blank=True, help_text='联系电话', max_length=20, null=True, verbose_name='联系电话')),
                ('operator', models.CharField(blank=True, help_text='经办人', max_length=200, null=True, verbose_name='经办人')),
                ('delivery_date', models.DateTimeField(blank=True, help_text='交货日期', null=True, verbose_name='交货日期')),
                ('depot', models.CharField(blank=True, help_text='仓库', max_length=200, null=True, verbose_name='仓库')),
                ('code', models.CharField(blank=True, help_text='编号', max_length=200, null=True, verbose_name='编号')),
                ('brand', models.CharField(blank=True, help_text='品名', max_length=200, null=True, verbose_name='品名')),
                ('specification', models.CharField(blank=True, help_text='规格', max_length=200, null=True, verbose_name='规格')),
                ('unit', models.CharField(blank=True, help_text='单位', max_length=20, null=True, verbose_name='单位')),
                ('price', models.CharField(blank=True, help_text='单价', max_length=20, null=True, verbose_name='单价')),
                ('total_price', models.CharField(blank=True, help_text='金额', max_length=20, null=True, verbose_name='金额')),
                ('production_date', models.DateTimeField(blank=True, help_text='生产日期', null=True, verbose_name='生产日期')),
                ('expired_date', models.DateTimeField(blank=True, help_text='有效期', null=True, verbose_name='有效期')),
                ('remark', models.CharField(blank=True, help_text='备注', max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('name', models.CharField(help_text='单位名称', max_length=20, null=True, unique=True, verbose_name='单位名称')),
                ('type', models.CharField(blank=True, help_text='单位名称', max_length=20, null=True, verbose_name='供应商分类')),
                ('tontact_phone', models.CharField(blank=True, help_text='联系电话', max_length=20, null=True, verbose_name='联系电话')),
                ('contact_name', models.CharField(blank=True, help_text='联系人', max_length=20, null=True, verbose_name='联系人')),
                ('address', models.CharField(blank=True, help_text='公司地址', max_length=200, null=True, verbose_name='公司地址')),
                ('account', models.CharField(blank=True, help_text='账户', max_length=20, null=True, verbose_name='账户')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='供应商', null=True, on_delete=django.db.models.deletion.PROTECT, to='new7.Supplier', verbose_name='供应商'),
        ),
    ]
