# Generated by Django 2.1 on 2018-09-23 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordergoods',
            old_name='goods',
            new_name='goods_id',
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='order_id',
            field=models.ForeignKey(blank=True, help_text='订单', null=True, on_delete=django.db.models.deletion.PROTECT, to='new7.Order', verbose_name='订单'),
        ),
    ]
