# Generated by Django 2.1 on 2018-08-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(help_text='单位名称', max_length=20, null=True, unique=True, verbose_name='票号')),
                ('tontact_phone', models.CharField(help_text='联系电话', max_length=20, null=True, unique=True, verbose_name='联系电话')),
                ('operator', models.CharField(help_text='经办人', max_length=20, null=True, unique=True, verbose_name='经办人')),
                ('delivery_date', models.DateTimeField(blank=True, help_text='交货日期', null=True, verbose_name='交货日期')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='单位名称', max_length=20, null=True, unique=True, verbose_name='单位名称')),
                ('type', models.CharField(help_text='单位名称', max_length=20, null=True, unique=True, verbose_name='供应商分类')),
                ('tontact_phone', models.CharField(help_text='联系电话', max_length=20, null=True, unique=True, verbose_name='联系电话')),
                ('contact_name', models.CharField(help_text='联系人', max_length=20, null=True, unique=True, verbose_name='联系人')),
                ('address', models.CharField(help_text='公司地址', max_length=20, null=True, unique=True, verbose_name='公司地址')),
                ('account', models.CharField(help_text='账户', max_length=20, null=True, unique=True, verbose_name='账户')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
