# Generated by Django 2.1 on 2018-11-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsrecord',
            name='spec',
            field=models.CharField(blank=True, help_text='规格', max_length=100, null=True, verbose_name='规格'),
        ),
    ]
