# Generated by Django 2.1 on 2018-08-26 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depot',
            options={'verbose_name': '仓库', 'verbose_name_plural': '仓库'},
        ),
        migrations.AlterField(
            model_name='depot',
            name='type',
            field=models.CharField(choices=[('main', '总库'), ('branch', '分库')], default='main', help_text='仓库类型', max_length=20, verbose_name='仓库类型'),
        ),
        migrations.AlterField(
            model_name='order',
            name='depot',
            field=models.ForeignKey(blank=True, help_text='仓库', null=True, on_delete=django.db.models.deletion.PROTECT, to='new7.Depot', verbose_name='仓库'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(blank=True, help_text='单价', max_length=200, null=True, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.CharField(blank=True, help_text='金额', max_length=200, null=True, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='order',
            name='unit',
            field=models.CharField(blank=True, help_text='单位', max_length=200, null=True, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='account',
            field=models.CharField(blank=True, help_text='账户', max_length=200, null=True, verbose_name='账户'),
        ),
    ]
