# Generated by Django 2.1 on 2018-11-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0002_goodsrecord_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('boss', '老板'), ('super_admin', '超级管理员'), ('admin', '管理员'), ('worker', '业务员'), ('warekeeper', '仓库管理员')], default='worker', help_text='角色', max_length=20, verbose_name='角色'),
        ),
    ]
