# Generated by Django 2.1 on 2018-08-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0002_auto_20180826_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('name', models.CharField(help_text='商品名称', max_length=100, null=True, unique=True, verbose_name='商品名称')),
                ('code', models.CharField(help_text='商品编码', max_length=100, null=True, unique=True, verbose_name='商品编码')),
                ('img', models.CharField(blank=True, help_text='商品图片', max_length=500, null=True, verbose_name='商品图片')),
                ('brand', models.CharField(blank=True, help_text='品牌', max_length=100, null=True, verbose_name='品牌')),
                ('in_price', models.CharField(blank=True, help_text='商品进价', max_length=100, null=True, verbose_name='商品进价')),
                ('sale_price', models.CharField(blank=True, help_text='商品售价', max_length=100, null=True, verbose_name='商品售价')),
                ('stock', models.CharField(blank=True, help_text='库存', max_length=100, null=True, verbose_name='库存')),
                ('unit', models.CharField(blank=True, help_text='单位', max_length=100, null=True, verbose_name='单位')),
                ('spec', models.CharField(blank=True, help_text='规格', max_length=100, null=True, verbose_name='规格')),
                ('desc', models.CharField(blank=True, help_text='描述', max_length=100, null=True, verbose_name='描述')),
                ('is_book', models.BooleanField(blank=True, default=False, help_text='是否预定', verbose_name='是否预定')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
            },
        ),
    ]
