# Generated by Django 2.1 on 2018-11-13 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0003_auto_20181110_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsDamaged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('count', models.IntegerField(default=0, help_text='数量', verbose_name='数量')),
                ('price', models.FloatField(blank=True, help_text='价格', null=True, verbose_name='价格')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='损失成本', max_digits=10, verbose_name='损失成本')),
                ('report_time', models.DateTimeField(blank=True, help_text='上报时间', null=True, verbose_name='上报时间')),
                ('remarks', models.TextField(blank=True, default='', help_text='备注', verbose_name='备注')),
                ('operator', models.CharField(help_text='操作员', max_length=20, null=True, verbose_name='操作员')),
                ('damaged_depot', models.ForeignKey(blank=True, help_text='所属仓库', null=True, on_delete=django.db.models.deletion.PROTECT, to='new7.Depot', verbose_name='所属仓库')),
                ('goods', models.ForeignKey(blank=True, help_text='商品', null=True, on_delete=django.db.models.deletion.PROTECT, to='new7.Goods', verbose_name='商品')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
