# Generated by Django 2.1 on 2018-09-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0003_auto_20180923_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, help_text='性别', verbose_name='性别'),
        ),
    ]
