# Generated by Django 2.1 on 2018-08-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0003_order_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='单位名称', max_length=20, null=True, unique=True, verbose_name='单位名称')),
                ('tontact_phone', models.CharField(help_text='联系电话', max_length=20, null=True, unique=True, verbose_name='联系电话')),
                ('contact_name', models.CharField(help_text='联系人', max_length=20, null=True, unique=True, verbose_name='联系人')),
                ('address', models.CharField(help_text='公司地址', max_length=20, null=True, unique=True, verbose_name='公司地址')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='仓库名称', max_length=20, null=True, unique=True, verbose_name='仓库名称')),
                ('type', models.CharField(choices=[('main', '在途'), ('branch', '总库')], default='main', help_text='所在位置类型', max_length=20, verbose_name='仓库类型')),
                ('stock', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='brand',
            field=models.CharField(blank=True, help_text='品名', max_length=20, null=True, verbose_name='品名'),
        ),
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, help_text='编号', max_length=20, null=True, verbose_name='编号'),
        ),
        migrations.AddField(
            model_name='order',
            name='depot',
            field=models.CharField(blank=True, help_text='仓库', max_length=20, null=True, verbose_name='仓库'),
        ),
        migrations.AddField(
            model_name='order',
            name='expired_date',
            field=models.DateTimeField(blank=True, help_text='有效期', null=True, verbose_name='有效期'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.CharField(blank=True, help_text='单价', max_length=20, null=True, verbose_name='单价'),
        ),
        migrations.AddField(
            model_name='order',
            name='production_date',
            field=models.DateTimeField(blank=True, help_text='生产日期', null=True, verbose_name='生产日期'),
        ),
        migrations.AddField(
            model_name='order',
            name='remark',
            field=models.CharField(blank=True, help_text='备注', max_length=500, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='order',
            name='specification',
            field=models.CharField(blank=True, help_text='规格', max_length=20, null=True, verbose_name='规格'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.CharField(blank=True, help_text='金额', max_length=20, null=True, verbose_name='金额'),
        ),
        migrations.AddField(
            model_name='order',
            name='unit',
            field=models.CharField(blank=True, help_text='单位', max_length=20, null=True, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.CharField(help_text='单位名称', max_length=100, null=True, unique=True, verbose_name='票号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='operator',
            field=models.CharField(blank=True, help_text='经办人', max_length=20, null=True, verbose_name='经办人'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tontact_phone',
            field=models.CharField(blank=True, help_text='联系电话', max_length=20, null=True, verbose_name='联系电话'),
        ),
    ]
