# Generated by Django 2.1 on 2018-08-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0003_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliver_address',
            field=models.CharField(blank=True, help_text='收货地址', max_length=200, null=True, verbose_name='收货地址'),
        ),
        migrations.AddField(
            model_name='order',
            name='deliver_money',
            field=models.CharField(blank=True, help_text='运费', max_length=200, null=True, verbose_name='运费'),
        ),
        migrations.AddField(
            model_name='order',
            name='deliver_type',
            field=models.CharField(blank=True, help_text='送货方式', max_length=200, null=True, verbose_name='送货方式'),
        ),
        migrations.AddField(
            model_name='order',
            name='flag',
            field=models.CharField(blank=True, help_text='订单有效标识', max_length=20, null=True, verbose_name='订单有效标识'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_closed',
            field=models.BooleanField(blank=True, default=False, help_text='订单是否完成', verbose_name='订单是否完成'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_pay',
            field=models.CharField(blank=True, help_text='是否支付', max_length=10, null=True, verbose_name='是否支付'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_refond',
            field=models.BooleanField(blank=True, default=False, help_text='是否退款', verbose_name='是否退款'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_unique',
            field=models.CharField(help_text='流水号', max_length=200, null=True, unique=True, verbose_name='流水号'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_from',
            field=models.CharField(blank=True, help_text='支付来源', max_length=200, null=True, verbose_name='支付来源'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_type',
            field=models.CharField(blank=True, help_text='支付方式', max_length=200, null=True, verbose_name='支付方式'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, help_text='订单状态', max_length=200, null=True, verbose_name='订单状态'),
        ),
        migrations.AddField(
            model_name='order',
            name='trade_no',
            field=models.CharField(blank=True, help_text='在线支付流水号', max_length=20, null=True, verbose_name='在线支付流水号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.CharField(help_text='票号', max_length=100, null=True, unique=True, verbose_name='票号'),
        ),
    ]
