# Generated by Django 2.1 on 2018-09-23 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0004_auto_20180923_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(blank=True, help_text='订单', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_goods', to='new7.Order', verbose_name='订单'),
        ),
    ]
