# Generated by Django 2.1 on 2018-11-13 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0004_goodsdamaged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsdamaged',
            name='count',
            field=models.IntegerField(help_text='数量', verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='goodsdamaged',
            name='damaged_depot',
            field=models.ForeignKey(help_text='所属仓库', on_delete=django.db.models.deletion.PROTECT, to='new7.Depot', verbose_name='所属仓库'),
        ),
        migrations.AlterField(
            model_name='goodsdamaged',
            name='goods',
            field=models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.PROTECT, to='new7.Goods', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='goodsdamaged',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='操作人员', null=True, on_delete=django.db.models.deletion.PROTECT, to='new7.Profile', verbose_name='操作人员'),
        ),
        migrations.AlterField(
            model_name='goodsdamaged',
            name='price',
            field=models.FloatField(help_text='价格', verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='goodsrecord',
            name='goods',
            field=models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.PROTECT, to='new7.Goods', verbose_name='商品'),
        ),
    ]
