# Generated by Django 2.1 on 2018-08-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0004_auto_20180826_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='stock',
            field=models.IntegerField(default=0, help_text='库存', verbose_name='库存'),
        ),
    ]
