# Generated by Django 2.1 on 2018-09-01 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('new7', '0004_auto_20180827_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('deleted', models.BooleanField(blank=True, default=False, help_text='是否已删除', verbose_name='是否已删除')),
                ('object_id', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('super_admin', '超级管理员'), ('admin', '管理员'), ('worker', '业务员'), ('warekeeper', '仓库管理员')], help_text='角色', max_length=20, verbose_name='角色')),
                ('phone', models.CharField(help_text='电话', max_length=20, verbose_name='电话')),
                ('name', models.CharField(help_text='姓名', max_length=20, verbose_name='姓名')),
                ('phone_verified', models.BooleanField(blank=True, default=False, help_text='电话是否已验证', verbose_name='电话是否已验证')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('depot', models.ForeignKey(blank=True, help_text='负责仓库', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depot_keepers', to='new7.Depot', verbose_name='负责仓库')),
                ('user', models.OneToOneField(help_text='用户', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '个人信息',
                'verbose_name_plural': '个人信息',
            },
        ),
    ]
