# Generated by Django 2.1 on 2018-09-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0005_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AddField(
            model_name='goods',
            name='short_name',
            field=models.CharField(blank=True, help_text='商品名称', max_length=100, null=True, verbose_name='商品简称'),
        ),
    ]
