# Generated by Django 2.1 on 2018-09-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0005_auto_20180923_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='desc',
            field=models.CharField(blank=True, help_text='描述', max_length=200, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='operator_name',
            field=models.CharField(blank=True, help_text='经办人电话', max_length=200, null=True, verbose_name='经办人电话'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='type',
            field=models.CharField(blank=True, choices=[('formal', '正规合作'), ('finance', '商铺合作'), ('stall', '摊贩合作')], default='a', help_text='供应商分类', max_length=20, verbose_name='供应商分类'),
        ),
    ]
