# Generated by Django 2.1 on 2018-11-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0005_auto_20181113_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='warn_stock',
            field=models.IntegerField(default=10, help_text='报警库存', verbose_name='报警库存'),
        ),
    ]
