# Generated by Django 2.1 on 2018-09-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0005_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
    ]
