# Generated by Django 2.1 on 2018-11-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0006_goods_warn_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsdamaged',
            name='remarks',
            field=models.TextField(default='', help_text='备注', verbose_name='备注'),
        ),
    ]
