# Generated by Django 2.1 on 2018-09-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0006_auto_20180924_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth',
            field=models.DateTimeField(blank=True, help_text='出生日期', null=True, verbose_name='出生日期'),
        ),
    ]
