# Generated by Django 2.1 on 2018-08-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0006_auto_20180826_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间'),
        ),
    ]
