# Generated by Django 2.1 on 2018-09-15 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0006_auto_20180915_1014'),
        ('new7', '0006_auto_20180909_1820'),
    ]

    operations = [
    ]
