# Generated by Django 2.1 on 2018-09-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0006_auto_20180915_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='cubage',
            field=models.IntegerField(default=0, help_text='容量', verbose_name='容量'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='short_name',
            field=models.CharField(blank=True, help_text='商品简称', max_length=100, null=True, verbose_name='商品简称'),
        ),
    ]
