# Generated by Django 2.1 on 2018-08-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0007_auto_20180826_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, help_text='公司地址', max_length=20, null=True, verbose_name='公司地址'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_name',
            field=models.CharField(blank=True, help_text='联系人', max_length=20, null=True, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tontact_phone',
            field=models.CharField(blank=True, help_text='联系电话', max_length=20, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='order',
            name='brand',
            field=models.CharField(blank=True, help_text='品名', max_length=200, null=True, verbose_name='品名'),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, help_text='编号', max_length=200, null=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='depot',
            field=models.CharField(blank=True, help_text='仓库', max_length=200, null=True, verbose_name='仓库'),
        ),
        migrations.AlterField(
            model_name='order',
            name='operator',
            field=models.CharField(blank=True, help_text='经办人', max_length=200, null=True, verbose_name='经办人'),
        ),
        migrations.AlterField(
            model_name='order',
            name='specification',
            field=models.CharField(blank=True, help_text='规格', max_length=200, null=True, verbose_name='规格'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='account',
            field=models.CharField(blank=True, help_text='账户', max_length=20, null=True, verbose_name='账户'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, help_text='公司地址', max_length=200, null=True, verbose_name='公司地址'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(blank=True, help_text='联系人', max_length=20, null=True, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tontact_phone',
            field=models.CharField(blank=True, help_text='联系电话', max_length=20, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='type',
            field=models.CharField(blank=True, help_text='单位名称', max_length=20, null=True, verbose_name='供应商分类'),
        ),
    ]
