# Generated by Django 2.1 on 2018-09-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0007_merge_20180915_1352'),
        ('new7', '0007_auto_20180915_1451'),
    ]

    operations = [
    ]
