# Generated by Django 2.1 on 2018-11-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0007_auto_20181117_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsdamaged',
            name='remarks',
            field=models.TextField(help_text='备注', verbose_name='备注'),
        ),
    ]
