# Generated by Django 2.1 on 2018-09-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0007_auto_20180915_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='account',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, help_text='地址', max_length=20, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.CharField(help_text='员工编号', max_length=200, null=True, unique=True, verbose_name='员工编号'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[(1, '男'), (2, '女')], default=1, help_text='性别', max_length=2, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='profile',
            name='salary',
            field=models.IntegerField(default=0, help_text='工资', verbose_name='工资'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='license_code',
            field=models.CharField(blank=True, help_text='执照编号', max_length=20, null=True, verbose_name='执照编号'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='operator',
            field=models.CharField(blank=True, help_text='经办人', max_length=200, null=True, verbose_name='经办人'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('super_admin', '超级管理员'), ('admin', '管理员'), ('worker', '业务员'), ('warekeeper', '仓库管理员')], default='worker', help_text='角色', max_length=20, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='type',
            field=models.CharField(blank=True, choices=[('a', '甲'), ('b', '乙'), ('c', '丙')], default='a', help_text='供应商分类', max_length=20, verbose_name='供应商分类'),
        ),
    ]
