# Generated by Django 2.1 on 2018-11-29 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0008_auto_20181117_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('name', models.CharField(help_text='店面名称', max_length=50, null=True, unique=True, verbose_name='店面名称')),
                ('type', models.CharField(choices=[('direct', '直营店'), ('extra', '外包店')], default='direct', help_text='店面类型', max_length=20, verbose_name='店面类型')),
                ('contact_phone', models.CharField(blank=True, help_text='联系电话', max_length=20, null=True, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, help_text='店面地址', max_length=100, null=True, verbose_name='店面地址')),
                ('staff_num', models.IntegerField(help_text='店面人数', verbose_name='店面人数')),
                ('contact_user', models.ForeignKey(blank=True, help_text='店面负责人', null=True, on_delete=django.db.models.deletion.PROTECT, to='new7.Profile', verbose_name='店面负责人')),
            ],
            options={
                'verbose_name': '店面',
                'verbose_name_plural': '店面',
            },
        ),
    ]
