# Generated by Django 2.1 on 2018-09-15 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0008_merge_20180915_1550'),
        ('new7', '0008_auto_20180915_1704'),
    ]

    operations = [
    ]
