# Generated by Django 2.1 on 2018-08-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0008_auto_20180826_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, help_text='地址', max_length=20, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='type',
            field=models.CharField(choices=[('main', '在途'), ('branch', '总库')], default='main', help_text='仓库类型', max_length=20, verbose_name='仓库类型'),
        ),
    ]
