# Generated by Django 2.1 on 2018-10-20 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0008_auto_20180924_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('record_type', models.CharField(choices=[('depot_in', '入库'), ('depot_out', '出库')], default='main', help_text='操作类型', max_length=20, verbose_name='记录类型')),
                ('count', models.IntegerField(default=0, help_text='数量', verbose_name='数量')),
                ('price', models.FloatField(blank=True, help_text='价格', null=True, verbose_name='价格')),
                ('unit', models.CharField(blank=True, help_text='单位', max_length=200, null=True, verbose_name='单位')),
                ('operator_account', models.CharField(help_text='操作员账号', max_length=20, null=True, verbose_name='操作员账号')),
                ('record_time', models.DateTimeField(blank=True, help_text='记录时间', null=True, verbose_name='记录时间')),
                ('record_source', models.CharField(blank=True, default='', help_text='操作来源', max_length=50, verbose_name='操作来源')),
                ('remarks', models.TextField(blank=True, default='', help_text='备注', verbose_name='备注')),
                ('goods', models.ForeignKey(blank=True, help_text='商品', null=True, on_delete=django.db.models.deletion.PROTECT, to='new7.Goods', verbose_name='商品')),
                ('record_depot', models.ForeignKey(blank=True, help_text='操作仓库', null=True, on_delete=django.db.models.deletion.PROTECT, to='new7.Depot', verbose_name='操作仓库')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
