# Generated by Django 2.1 on 2018-10-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0009_goodsrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergoods',
            name='price',
            field=models.FloatField(blank=True, help_text='价格', null=True, verbose_name='价格'),
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='unit',
            field=models.CharField(blank=True, help_text='单位', max_length=200, null=True, verbose_name='单位'),
        ),
    ]
