# Generated by Django 2.1 on 2018-11-29 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0009_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(help_text='店面地址', max_length=100, verbose_name='店面地址'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='contact_phone',
            field=models.CharField(help_text='联系电话', max_length=20, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='contact_user',
            field=models.ForeignKey(help_text='店面负责人', on_delete=django.db.models.deletion.PROTECT, to='new7.Profile', verbose_name='店面负责人'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(help_text='店面名称', max_length=50, unique=True, verbose_name='店面名称'),
        ),
    ]
