# Generated by Django 2.1 on 2018-12-01 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0010_auto_20181129_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsrecord',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='店面', null=True, on_delete=django.db.models.deletion.PROTECT, to='new7.Shop', verbose_name='店面'),
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='店面', null=True, on_delete=django.db.models.deletion.PROTECT, to='new7.Shop', verbose_name='店面'),
        ),
    ]
