# Generated by Django 2.1 on 2018-10-21 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0010_auto_20181021_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsrecord',
            name='order',
            field=models.ForeignKey(blank=True, help_text='所属订单', null=True, on_delete=django.db.models.deletion.PROTECT, to='new7.Order', verbose_name='所属订单'),
        ),
        migrations.AddField(
            model_name='order',
            name='record_type',
            field=models.CharField(choices=[('depot_in', '入库'), ('depot_out', '出库')], default='main', help_text='操作类型', max_length=20, verbose_name='记录类型'),
        ),
    ]
