# Generated by Django 2.1 on 2018-10-21 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0011_auto_20181021_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='record_type',
            new_name='order_type',
        ),
    ]
