# Generated by Django 2.1 on 2018-12-03 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0011_auto_20181201_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsdamaged',
            name='damaged_shop',
            field=models.ForeignKey(blank=True, help_text='所属店面', null=True, on_delete=django.db.models.deletion.PROTECT, to='new7.Shop', verbose_name='所属店面'),
        ),
        migrations.AlterField(
            model_name='goodsdamaged',
            name='damaged_depot',
            field=models.ForeignKey(blank=True, help_text='所属仓库', null=True, on_delete=django.db.models.deletion.PROTECT, to='new7.Depot', verbose_name='所属仓库'),
        ),
    ]
