# Generated by Django 2.1 on 2018-10-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0012_auto_20181021_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('depot_in', '入库'), ('depot_out', '出库')], help_text='订单类型', max_length=20, verbose_name='订单类型'),
        ),
    ]
