# Generated by Django 2.1 on 2018-12-09 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0012_auto_20181203_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsrecord',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='过期日期', null=True, verbose_name='过期日期'),
        ),
        migrations.AddField(
            model_name='goodsrecord',
            name='production_date',
            field=models.DateField(blank=True, help_text='生产日期', null=True, verbose_name='生产日期'),
        ),
        migrations.AddField(
            model_name='goodsrecord',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='供应商', null=True, on_delete=django.db.models.deletion.PROTECT, to='new7.Supplier', verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='过期日期', null=True, verbose_name='过期日期'),
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='production_date',
            field=models.DateField(blank=True, help_text='生产日期', null=True, verbose_name='生产日期'),
        ),
    ]
