# Generated by Django 2.1 on 2018-12-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0014_supplier_common_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='common_used',
            field=models.BooleanField(default=True, help_text='是否可以被普通员工所用'),
        ),
    ]
