# Generated by Django 2.1 on 2018-11-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0014_auto_20181024_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='stock_status',
            field=models.IntegerField(default=1, help_text='库存状态', verbose_name='库存状态'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='short_name',
            field=models.CharField(help_text='商品简称', max_length=100, null=True, verbose_name='商品简称'),
        ),
    ]
