# Generated by Django 2.1 on 2018-11-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0015_auto_20181102_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='short_name',
            field=models.CharField(blank=True, help_text='商品简称', max_length=100, null=True, verbose_name='商品简称'),
        ),
    ]
