# Generated by Django 2.1 on 2018-12-29 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0016_shopincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsrecord',
            name='order',
            field=models.ForeignKey(blank=True, help_text='所属订单', null=True, on_delete=django.db.models.deletion.CASCADE, to='new7.Order', verbose_name='所属订单'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(blank=True, help_text='订单', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_goods', to='new7.Order', verbose_name='订单'),
        ),
    ]
