# Generated by Django 2.1 on 2018-11-02 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0018_auto_20181102_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='last_operate_time',
            field=models.DateTimeField(blank=True, help_text='上次操作时间', null=True, verbose_name='上次操作时间'),
        ),
        migrations.AddField(
            model_name='goods',
            name='last_operate_type',
            field=models.CharField(choices=[('depot_in', '入库'), ('depot_out', '出库')], help_text='最近操作类型', max_length=20, null=True, verbose_name='最近操作类型'),
        ),
        migrations.AddField(
            model_name='goods',
            name='last_operator',
            field=models.ForeignKey(blank=True, help_text='最近操作人', null=True, on_delete=django.db.models.deletion.PROTECT, to='new7.Profile', verbose_name='最近操作人'),
        ),
        migrations.AddField(
            model_name='goodsrecord',
            name='leave_count',
            field=models.IntegerField(default=0, help_text='出库数量', verbose_name='出库数量'),
        ),
        migrations.AlterField(
            model_name='goodsrecord',
            name='record_type',
            field=models.CharField(choices=[('depot_in', '入库'), ('depot_out', '出库')], default='depot_in', help_text='操作类型', max_length=20, verbose_name='记录类型'),
        ),
    ]
