# Generated by Django 2.1 on 2019-01-05 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0019_auto_20190105_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergoods',
            name='from_depot',
            field=models.ForeignKey(blank=True, help_text='来源仓库', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_depot1', to='new7.Depot', verbose_name='来源仓库'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='operate_depot',
            field=models.ForeignKey(blank=True, help_text='操作仓库', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operate_depot', to='new7.Depot', verbose_name='操作仓库'),
        ),
    ]
