# Generated by Django 2.1 on 2018-11-03 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0019_auto_20181102_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='order',
            name='code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='expired_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='production_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='specification',
        ),
        migrations.RemoveField(
            model_name='order',
            name='unit',
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='operate_depot',
            field=models.ForeignKey(blank=True, help_text='操作仓库', null=True, on_delete=django.db.models.deletion.PROTECT, to='new7.Depot', verbose_name='操作仓库'),
        ),
    ]
