# Generated by Django 2.1 on 2019-01-05 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0020_auto_20190105_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergoods',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='供应商', null=True, on_delete=django.db.models.deletion.PROTECT, to='new7.Supplier', verbose_name='供应商'),
        ),
    ]
