# Generated by Django 2.1 on 2018-11-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0020_auto_20181103_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='价格', max_digits=10, verbose_name='价格'),
        ),
    ]
