# Generated by Django 2.1 on 2019-01-05 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0021_ordergoods_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopincome',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='操作人员', null=True, on_delete=django.db.models.deletion.PROTECT, to='new7.Profile', verbose_name='操作人员'),
        ),
    ]
