# Generated by Django 2.1 on 2019-01-08 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0022_shopincome_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('stock', models.IntegerField(default=0, help_text='库存', verbose_name='库存')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='商品价格', max_digits=10, verbose_name='商品价格')),
                ('goods', models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, to='new7.Goods', verbose_name='商品')),
                ('operator', models.ForeignKey(blank=True, help_text='操作人员', null=True, on_delete=django.db.models.deletion.PROTECT, to='new7.Profile', verbose_name='操作人员')),
                ('shop', models.ForeignKey(help_text='店面', on_delete=django.db.models.deletion.CASCADE, to='new7.Shop', verbose_name='店面')),
            ],
            options={
                'verbose_name': '店面盘点',
                'verbose_name_plural': '店面盘点',
            },
        ),
    ]
