# Generated by Django 2.1 on 2019-01-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0025_auto_20190108_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='cubage',
            field=models.FloatField(default=0, help_text='容量', verbose_name='容量'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='stock',
            field=models.FloatField(default=0, help_text='库存', verbose_name='库存'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='warn_stock',
            field=models.FloatField(default=10, help_text='报警库存', verbose_name='报警库存'),
        ),
        migrations.AlterField(
            model_name='goodsdamaged',
            name='count',
            field=models.FloatField(help_text='数量', verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='goodsrecord',
            name='count',
            field=models.FloatField(default=0, help_text='数量', verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='goodsrecord',
            name='leave_count',
            field=models.FloatField(default=0, help_text='出库数量', verbose_name='出库数量'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='count',
            field=models.FloatField(default=1, help_text='数量', verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salary',
            field=models.FloatField(default=0, help_text='工资', verbose_name='工资'),
        ),
        migrations.AlterField(
            model_name='shopinventory',
            name='stock',
            field=models.FloatField(default=0, help_text='库存', verbose_name='库存'),
        ),
    ]
