# Generated by Django 2.1 on 2019-02-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0030_auto_20190131_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinventory',
            name='month',
            field=models.IntegerField(default=0, help_text='月份'),
        ),
    ]
