# Generated by Django 2.1 on 2019-02-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new7', '0031_shopinventory_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinventory',
            name='amount',
            field=models.FloatField(default=0, help_text='商品成本', verbose_name='商品成本'),
        ),
    ]
